global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'users:8080' ]
  - job_name: 'books'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'books:8081' ]
  - job_name: 'rentals'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rentals:8082' ]
  - job_name: 'message'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'message:8083' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
  
