services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  usersdb:
    container_name: usersdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: usersdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  booksdb:
    container_name: booksdb
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: booksdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "configserver"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "eurekaserver"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  users:
    image: "users"
    container_name: users-ms
    ports:
      - "8080:8080"
    depends_on:
      usersdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "users"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://usersdb:5432/usersdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  books:
    image: "library-book"
    container_name: books-ms
    ports:
      - "8090:8090"
    depends_on:
      booksdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "books"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://booksdb:5432/booksdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  library:
    driver: "bridge"