server:
  port: 8084
spring:
  application:
    name: "books"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5434/booksdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    function:
      definition: borrowBook;returnBook
    stream:
      bindings:
        borrowBook-in-0:
          destination: borrow-book
          group: ${spring.application.name}
        returnBook-in-0:
          destination: return-book
          group: ${spring.application.name}
        bookAvailable-out-0:
          destination: book-available
        bookUnavailable-out-0:
          destination: book-unavailable
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
