apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentals-deployment
  labels:
    app: rentals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentals
  template:
    metadata:
      labels:
        app: rentals
    spec:
      containers:
      - name: rentals
        image: janzkolna/rentals
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: library-configmap
              key: RENTALS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: library-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: library-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: library-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: library-configmap
              key: RENTALS_DATASOURCE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: rentals
spec:
  selector:
    app: rentals
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
